apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # Base64 String: superman@google.com = c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  # Base64 String: EstoEsUnPassWordSecreto = RXN0b0VzVW5QYXNzV29yZFNlY3JldG8=
  DB_PASSWORD: RXN0b0VzVW5QYXNzV29yZFNlY3JldG8=