apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # Base64 String: postgres = cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  # Base64 String: RXN0b0VzVW5QYXNzV29yZFNlY3JldG8=
  DB_PASSWORD: RXN0b0VzVW5QYXNzV29yZFNlY3JldG8=